version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weba_books
    ports:
      - "3307:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend_app
    restart: always
    ports:
      - "4444:4444"
    volumes:
      - log_volume:/log
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=weba_books
      - PORT=4444
      - LOGGER_CONFIG={"target":"pino-pretty","options":{"colorize":true}}

  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_gui
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db

volumes:
  mysql_data:
  log_volume: