version: '3.8'

services:
  db:
    image: mysql:latest 
    container_name: mysql_db_container 
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: pass2023 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin:latest 
    container_name: phpmyadmin_gui_container 
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db 
      PMA_PORT: 3306
      PMA_USER: root 
      PMA_PASSWORD: pass2023 
    networks:
      - app_network

networks:
  app_network:
    driver: bridge 

volumes:
  db_data: 
